export type SectorType =
  | "Commercial Banks"
  | "Development Banks"
  | "Finance"
  | "Hotels And Tourism"
  | "Hydro Power"
  | "Investment"
  | "Life Insurance"
  | "Manufacturing And Processing"
  | "Microfinance"
  | "Mutual Fund"
  | "Non-Life Insurance"
  | "Others"

// Map of company symbols to their sectors
export const sectorMap: Record<string, SectorType> = {
  // Commercial Banks
  ADBL: "Commercial Banks",
  CZBIL: "Commercial Banks",
  EBL: "Commercial Banks",
  GBIME: "Commercial Banks",
  HBL: "Commercial Banks",
  KBL: "Commercial Banks",
  MBL: "Commercial Banks",
  NABIL: "Commercial Banks",
  NBL: "Commercial Banks",
  NICA: "Commercial Banks",
  NMB: "Commercial Banks",
  PCBL: "Commercial Banks",
  SANIMA: "Commercial Banks",
  SBI: "Commercial Banks",
  SBL: "Commercial Banks",
  SCB: "Commercial Banks",
  PRVU: "Commercial Banks",
  NIMB: "Commercial Banks",
  LSL: "Commercial Banks",

  // Development Banks
  CORBL: "Development Banks",
  EDBL: "Development Banks",
  GBBL: "Development Banks",
  JBBL: "Development Banks",
  MDB: "Development Banks",
  MNBBL: "Development Banks",
  NABBC: "Development Banks",
  SADBL: "Development Banks",
  SHINE: "Development Banks",
  SINDU: "Development Banks",
  GRDBL: "Development Banks",
  KRBL: "Development Banks",
  MLBL: "Development Banks",
  LBBL: "Development Banks",
  KSBBL: "Development Banks",
  SAPDBL: "Development Banks",

  // Finance
  CFCL: "Finance",
  GFCL: "Finance",
  GMFIL: "Finance",
  ICFC: "Finance",
  JFL: "Finance",
  MFIL: "Finance",
  MPFL: "Finance",
  NFS: "Finance",
  PFL: "Finance",
  PROFL: "Finance",
  SIFC: "Finance",
  RLFL: "Finance",
  GUFL: "Finance",
  BFC: "Finance",
  SFCL: "Finance",

  // Hotels And Tourism
  OHL: "Hotels And Tourism",
  SHL: "Hotels And Tourism",
  TRH: "Hotels And Tourism",
  CGH: "Hotels And Tourism",
  KDL: "Hotels And Tourism",
  CITY: "Hotels And Tourism",
  BANDIPUR: "Hotels And Tourism",

  // Hydro Power
  AHPC: "Hydro Power",
  BPCL: "Hydro Power",
  CHCL: "Hydro Power",
  NHPC: "Hydro Power",
  SHPC: "Hydro Power",
  HURJA: "Hydro Power",
  AKPL: "Hydro Power",
  BARUN: "Hydro Power",
  API: "Hydro Power",
  NGPL: "Hydro Power",
  MHL: "Hydro Power",
  NYADI: "Hydro Power",
  SJCL: "Hydro Power",
  RHPL: "Hydro Power",
  UMHL: "Hydro Power",
  DORDI: "Hydro Power",
  PHCL: "Hydro Power",
  PPL: "Hydro Power",
  UPCL: "Hydro Power",
  SPL: "Hydro Power",
  SPDL: "Hydro Power",
  MKJC: "Hydro Power",
  SAHAS: "Hydro Power",
  KKHC: "Hydro Power",
  HPPL: "Hydro Power",
  DHPL: "Hydro Power",
  BHPL: "Hydro Power",
  MHNL: "Hydro Power",
  CHL: "Hydro Power",
  USHL: "Hydro Power",
  SPHL: "Hydro Power",
  NHDL: "Hydro Power",
  RADHI: "Hydro Power",
  BNHC: "Hydro Power",
  RHGCL: "Hydro Power",
  KPCL: "Hydro Power",
  TAMOR: "Hydro Power",
  GHL: "Hydro Power",
  EHPL: "Hydro Power",
  MKHC: "Hydro Power",
  BEDC: "Hydro Power",
  PMHPL: "Hydro Power",
  KBSH: "Hydro Power",
  MBJC: "Hydro Power",
  GLH: "Hydro Power",
  USHEC: "Hydro Power",
  AKJCL: "Hydro Power",
  LEC: "Hydro Power",
  TPC: "Hydro Power",
  SHEL: "Hydro Power",
  PPCL: "Hydro Power",
  TSHL: "Hydro Power",
  SSHL: "Hydro Power",
  JOSHI: "Hydro Power",
  UPPER: "Hydro Power",
  TVCL: "Hydro Power",
  UNHPL: "Hydro Power",
  SPC: "Hydro Power",
  SGHC: "Hydro Power",
  AHL: "Hydro Power",
  BHDC: "Hydro Power",
  HDHPC: "Hydro Power",
  MHCL: "Hydro Power",
  SMH: "Hydro Power",
  RFPL: "Hydro Power",
  MEN: "Hydro Power",
  UHEWA: "Hydro Power",
  HHL: "Hydro Power",
  UMRH: "Hydro Power",
  SIKLES: "Hydro Power",
  MEL: "Hydro Power",
  RURU: "Hydro Power",
  MAKAR: "Hydro Power",
  DHEL: "Hydro Power",
  SMJC: "Hydro Power",
  MKHL: "Hydro Power",
  CKHL: "Hydro Power",
  MMKJL: "Hydro Power",
  DOLTI: "Hydro Power",
  BHL: "Hydro Power",
  GVL: "Hydro Power",
  MSHL: "Hydro Power",
  BUNGAL: "Hydro Power",
  RIDI: "Hydro Power",
  HIMSTAR: "Hydro Power",
  MEHL: "Hydro Power",
  IHL: "Hydro Power",
  SMHL: "Hydro Power",
  MCHL: "Hydro Power",
  BHCL: "Hydro Power",
  SANVI: "Hydro Power",
  RAWA: "Hydro Power",
  ULHC: "Hydro Power",
  BGWT: "Hydro Power",
  MANDU: "Hydro Power",
  MABEL: "Hydro Power",
  VLUCL: "Hydro Power",

  // Investment
  CIT: "Investment",
  HATHY: "Investment",
  HIDCL: "Investment",
  NIFRA: "Investment",
  ENL: "Investment",
  NRN: "Investment",
  CHDC: "Investment",

  // Life Insurance
  ALICL: "Life Insurance",
  LICN: "Life Insurance",
  NLIC: "Life Insurance",
  NLICL: "Life Insurance",
  CLI: "Life Insurance",
  RNLI: "Life Insurance",
  ILI: "Life Insurance",
  SNLI: "Life Insurance",
  SJLIC: "Life Insurance",
  SRLI: "Life Insurance",
  HLI: "Life Insurance",
  PMLI: "Life Insurance",
  GMLI: "Life Insurance",
  CREST: "Life Insurance",
  RJBCL: "Life Insurance",

  // Manufacturing And Processing
  BNL: "Manufacturing And Processing",
  BNT: "Manufacturing And Processing",
  HDL: "Manufacturing And Processing",
  UNL: "Manufacturing And Processing",
  SHIVM: "Manufacturing And Processing",
  SARBTM: "Manufacturing And Processing",
  RSML: "Manufacturing And Processing",
  SONA: "Manufacturing And Processing",
  OMPL: "Manufacturing And Processing",
  GCIL: "Manufacturing And Processing",
  SAGAR: "Manufacturing And Processing",
  SAIL: "Manufacturing And Processing",
  SYPNL: "Manufacturing And Processing",
  NLO: "Manufacturing And Processing",

  // Microfinance
  CBBL: "Microfinance",
  DDBL: "Microfinance",
  FMDBL: "Microfinance",
  KMCDB: "Microfinance",
  NUBL: "Microfinance",
  SKBBL: "Microfinance",
  SLBBL: "Microfinance",
  SWBBL: "Microfinance",
  MLBBL: "Microfinance",
  LLBS: "Microfinance",
  JSLBB: "Microfinance",
  VLBS: "Microfinance",
  RSDC: "Microfinance",
  NMBMF: "Microfinance",
  MERO: "Microfinance",
  NADEP: "Microfinance",
  ALBSL: "Microfinance",
  NMFBS: "Microfinance",
  GMFBS: "Microfinance",
  HLBSL: "Microfinance",
  ILBS: "Microfinance",
  FOWAD: "Microfinance",
  SMATA: "Microfinance",
  MSLB: "Microfinance",
  GILB: "Microfinance",
  SMB: "Microfinance",
  GBLBS: "Microfinance",
  NESDO: "Microfinance",
  MLBSL: "Microfinance",
  GLBSL: "Microfinance",
  NICLBSL: "Microfinance",
  SLBSL: "Microfinance",
  UNLB: "Microfinance",
  SWASTIK: "Microfinance",
  JBLB: "Microfinance",
  SHLB: "Microfinance",
  ULBSL: "Microfinance",
  SMFBS: "Microfinance",
  WNLB: "Microfinance",
  SAMAJ: "Microfinance",
  DLBS: "Microfinance",
  ANLB: "Microfinance",
  MLBS: "Microfinance",
  AVYAN: "Microfinance",
  ACLBSL: "Microfinance",
  USLB: "Microfinance",
  CYCL: "Microfinance",
  SWMF: "Microfinance",
  NMLBBL: "Microfinance",
  MATRI: "Microfinance",
  SMPDA: "Microfinance",

  // Mutual Fund
  SEF: "Mutual Fund",
  SAEF: "Mutual Fund",
  NBF2: "Mutual Fund",
  CMF2: "Mutual Fund",
  NIBLSF: "Mutual Fund",
  NMB50: "Mutual Fund",
  SIGS2: "Mutual Fund",
  NICBF: "Mutual Fund",
  SFMF: "Mutual Fund",
  LUK: "Mutual Fund",
  NADDF: "Mutual Fund",
  SLCF: "Mutual Fund",
  KEF: "Mutual Fund",
  SBCF: "Mutual Fund",
  NIBSF2: "Mutual Fund",
  PSF: "Mutual Fund",
  NICSF: "Mutual Fund",
  SSIS: "Mutual Fund",
  RMF1: "Mutual Fund",
  MMF1: "Mutual Fund",
  NMBSBFE: "Mutual Fund",
  NBF3: "Mutual Fund",
  KDBY: "Mutual Fund",
  NICFC: "Mutual Fund",
  GIBF1: "Mutual Fund",
  SLK: "Mutual Fund",
  NSIF2: "Mutual Fund",
  SAGF: "Mutual Fund",
  NFCF: "Mutual Fund",
  NIBLGF: "Mutual Fund",
  SFEF: "Mutual Fund",
  PRSF: "Mutual Fund",
  KSLY: "Mutual Fund",
  SIGS3: "Mutual Fund",
  C30MF: "Mutual Fund",
  RMF2: "Mutual Fund",
  LVF2: "Mutual Fund",
  H8020: "Mutual Fund",
  NICGF2: "Mutual Fund",
  NIBLSTF: "Mutual Fund",
  KSY: "Mutual Fund",
  MNMF1: "Mutual Fund",
  GSY: "Mutual Fund",
  NMBHF2: "Mutual Fund",
  SFF: "Mutual Fund",
  MBLEF: "Mutual Fund",
  RSY: "Mutual Fund",
  PSIS: "Mutual Fund",
  GBIMESY2: "Mutual Fund",
  CSY: "Mutual Fund",
  ELIS: "Mutual Fund",
  NI31: "Mutual Fund",
  RBBF40: "Mutual Fund",
  HLICF: "Mutual Fund",

  // Non-Life Insurance
  NICL: "Non-Life Insurance",
  NIL: "Non-Life Insurance",
  NLG: "Non-Life Insurance",
  SICL: "Non-Life Insurance",
  PRIN: "Non-Life Insurance",
  RBCL: "Non-Life Insurance",
  IGI: "Non-Life Insurance",
  HEI: "Non-Life Insurance",
  SGIC: "Non-Life Insurance",
  SPIL: "Non-Life Insurance",
  SALICO: "Non-Life Insurance",
  UAIL: "Non-Life Insurance",
  NMIC: "Non-Life Insurance",

  // Others
  NTC: "Others",
  NRIC: "Others",
  HRL: "Others",
  MKCL: "Others",
  TTL: "Others",
  JHAPA: "Others",
  NRM: "Others",
  PURE: "Others",
  NWCL: "Others",
}

export function getSectorForSymbol(symbol: string): SectorType | null {
  return sectorMap[symbol] || null
}

export function groupStocksBySector<T extends { symbol: string }>(stocks: T[]): Record<SectorType, T[]> {
  const sectors: Record<SectorType, T[]> = {
    "Commercial Banks": [],
    "Development Banks": [],
    Finance: [],
    "Hotels And Tourism": [],
    "Hydro Power": [],
    Investment: [],
    "Life Insurance": [],
    "Manufacturing And Processing": [],
    Microfinance: [],
    "Mutual Fund": [],
    "Non-Life Insurance": [],
    Others: [],
  }

  stocks.forEach((stock) => {
    const sector = getSectorForSymbol(stock.symbol)
    if (sector) {
      sectors[sector].push(stock)
    }
  })

  return sectors
}